#pragma once

// donut includes
#include <base/log.h>

namespace donut
{
	#define __INPUT_PRINT_NAMESPACE "INPUT"
	
	// Printing macros
	#define INPUT_DEBUG(ENONCE) PRINT_DEBUG (__INPUT_PRINT_NAMESPACE, ENONCE)
	#define INPUT_WARNING(ENONCE) PRINT_WARNING (__INPUT_PRINT_NAMESPACE, ENONCE)
	#define INPUT_INFO(ENONCE) PRINT_INFO (__INPUT_PRINT_NAMESPACE, ENONCE)
	#define INPUT_ERROR(ENONCE) PRINT_ERROR (__INPUT_PRINT_NAMESPACE, ENONCE)	
}