#pragma once

// donut includes
#include <base/log.h>

namespace donut
{
	#define __STATE_ENGINE_PRINT_NAMESPACE "STATE_ENGINE"
	
	// Printing macros
	#define STATE_ENGINE_DEBUG(ENONCE) PRINT_DEBUG (__STATE_ENGINE_PRINT_NAMESPACE, ENONCE)
	#define STATE_ENGINE_WARNING(ENONCE) PRINT_WARNING (__STATE_ENGINE_PRINT_NAMESPACE, ENONCE)
	#define STATE_ENGINE_INFO(ENONCE) PRINT_INFO (__STATE_ENGINE_PRINT_NAMESPACE, ENONCE)
	#define STATE_ENGINE_ERROR(ENONCE) PRINT_ERROR (__STATE_ENGINE_PRINT_NAMESPACE, ENONCE)	
}